#!/usr/bin/env bash

session_name=Relax

tmux has-session -t $session_name 2>/dev/null
if [ "$?" -eq 1 ] ; then
    tmux source-file $HOME/.config/i3/stuff/tmux/tmux.conf
    tmux new-session -d -s $session_name
    tmux select-pane -t 0
    tmux split-window -h
    tmux select-pane -t 1
    tmux send-keys "cmus" C-m 
    tmux split-window -v
    
    tmux select-pane -t 0
    tmux split-window -v
    tmux select-pane -t 1
    tmux send-keys "pipes.sh" C-m
    tmux select-pane -t 3
    sleep 1
    tmux send-keys "vis" C-m 
fi

tmux attach-session -t $session_name
